### ISSUE TITLE
Update Custom to have parity with Core

### ISSUE THREAD

**Issue by lallmon** [tachyons-css/tachyons-custom#3]
@mrmrs 

I believe @jeffmicklos and I were going to tackle this, and maybe you can check this, but it looks like the only places that have variables are in

```
_border_colors.css
_border_radius.css
_border_width.css
_box_shadow.css
_font_family.css
_height.css
_letter_spacing.css
_line_height.css
_max_widths.css
_skins-pseudo.css
_skins.css
_spacing.css
_tables.css
_type-scale.css
_widths.css
```

might it make sense to submodule core, and import the ones that don't, then reconcile the ones with vars?

What way have you done this previously?

**Comment by mrmrs** [comment]
I am not that smart so take my opinion with a grain of salt but submoduling anything has never turned out to be a good idea. 

I mostly automate these things with vim and generally am behind on keeping all things in sync because I only use the main tachyons project. Other auxiliary things are largely because I think they make sense but not necessarily something I personally need. I am open to any automation technique you will suggest, but yeah in my experience submodules cause more problems than they solve. 

- Adam

**Comment by hacknug** [comment]
I have an updated fork without submodules or anything else. Just the regular Tachyons Custom with every fix and feature from the regular one (plus some white-spaces cleanup). I can submit a PR if you want me to.

**Comment by aanomm** [comment]
Are there any plans to keep Tachy Custom in-sync with Tachy core?

**Comment by scottcorgan** [comment]
I feel like custom should just be how core is built.

Thoughts? (not sure if that's been discussed before)

**Comment by Chrisedmo** [comment]
Just submitted a pull request to keep this up to date with the tachyons core as of writing (4.8.1)

#7

**Comment by johno** [comment]
Everything is now in sync thanks to @Chrisedmo.
